name: whisky_auctions_viewer
description: Flutter Riverpod Sample using Whisky Hunter API

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: 3.3.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Riverpod
  riverpod: ^2.0.2
  flutter_riverpod: ^2.0.2

  # freezed
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  # go_router
  go_router: ^5.1.1

  # dio
  dio: ^4.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.3.2

  # freezed
  freezed: ^2.2.0
  json_serializable: ^6.5.3
  

flutter:
  uses-material-design: true

fonts:
  - family: Noto Sans JP
    fonts:
      - assets: assets/fonts/NotoSansJP-Regular.otf